#############################################################################################
# This pipeline first runs Python code to generate a network based off the dblp
# format. It pickles the network and also writes it out in the correct format to be
# fed into the C++ code. The C++ code then generates vectors based off the network file
# generated by the before_vectors python pipeline. The after_vectors python pipeline
# then reads in the vectors and unpickles the network created in before_vectors in order to
# ensure the node indices match up. It then performs clustering and cluster analysis using
# the unpickled network and the vectors.
#############################################################################################
python3 clustering_pipeline.py before_vectors
cd C++\ code/
g++ main.cpp -o main -std=c++11
echo "../data/dblp/edgelist.txt" "../data/dblp/vectors.txt" $1 $2 "y"| ./main
cd ..
python3 clustering_pipeline.py after_vectors
